name = "adare_net_examples"
description = "Adare_Net examples"
version = "0.15.7-dev"

authors = ["Daniel Norte de Moraes"]
maintainers = ["Daniel Norte de Moraes <danieagle@tutanota.com>"]
maintainers-logins = ["danieagle"]

executables = ["test_get_multi_addresses",
  "tcp_server_new", "tcp_client_new",
  "udp_server_new", "udp_client_new"]

[build-switches]
"*".Ada_Version = "Ada12"
"*".Style_checks = ["-gnaty2abCefhiklnprstmM137"]
[[depends-on]]
adare_net = "~0.8.3-dev"
[[pins]]
adare_net = { path='..' }
