name = "adare_net_examples"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Daniel Norte de Moraes"]
maintainers = ["Daniel Norte de Moraes <danieagle@tutanota.com>"]
maintainers-logins = ["danieagle"]

executables = ["tcp_server", "tcp_client", "udp_server", "udp_client"]

[build-switches]
"*".Ada_Version = "Ada12"
[[depends-on]]
adare_net = "~0.1.0-dev"
[[pins]]
adare_net = { path='../adare_net' }
