/* Configuration for adare_net generated by Alire */
#ifndef ADARE_NET_CONFIG_H
#define ADARE_NET_CONFIG_H

#define CRATE_VERSION "0.1.1-dev"
#define CRATE_NAME "adare_net"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
